[kovi-plugin-cmd]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-cmd.access_list]
friends = []
groups = []

[issues]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[issues.access_list]
friends = []
groups = []

[echo]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[echo.access_list]
friends = []
groups = []

[message_route]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[message_route.access_list]
friends = []
groups = []
