[echo]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[echo.access_list]
friends = []
groups = []

[kovi-plugin-cmd]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-cmd.access_list]
friends = []
groups = []

[addissue]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[addissue.access_list]
friends = []
groups = []
